@startuml

[IdP Implementor]

[Blockchain]

[IdP Implementor] .. [Blockchain] : ID data PUT

[DataStore]
[DataStore API]
[DataStore API] .. [DataStore] : allows access to

[PDM UI]
[PDM UI] .. [Blockchain] : ID data GET
[PDM UI] .. [Blockchain] : PDM subsnap GET and PUT
[PDM UI] .. [Blockchain] : auth GET and PUT
[PDM UI] .. [DataStore API] : subsnap GET and PUT

@enduml
